openapi: 3.0.0
x-stoplight:
  id: 80o1yi82d2urj
info:
  title: e-procurement
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas:
    ProductCategory:
      type: object
      properties:
        id:
          type: string
        description:
          type: string
        bought:
          type: string
          enum:
            - 'no'
            - 'yes'
        sold:
          type: string
          enum:
            - 'no'
            - 'yes'
      x-examples:
        example-1:
          id: BMSOL
          description: Purchased/Manufactured/Sold
          bought: 'yes'
          sold: 'no'
    Product:
      title: Product
      x-stoplight:
        id: 87z6sz5xl6la4
      type: object
      x-examples: {}
      properties:
        id:
          type: string
        category:
          $ref: '#/components/schemas/ProductCategory'
        type:
          type: string
          enum:
            - stockManagement
            - consumable
            - service
        sealesPrice:
          type: number
        salesTax:
          type: string
          enum:
            - 20% (Bien)
            - 0% EXO (Bien)
            - 20% (Service)
            - 0% EXO (Service)
        cost:
          type: number
